### ISSUE TITLE
导出异常： workbook.parse()中初始化BOFRecord时内部发生数组下标越界

### ISSUE THREAD

**Issue by StableMutation** [DmrfCoder/AndroidExcelDemo#1]
@DmrfCoder 
W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
W/System.err:     at jxl.read.biff.BOFRecord.<init>(BOFRecord.java:81)
        at jxl.read.biff.WorkbookParser.parse(WorkbookParser.java:548)

    BOFRecord(Record t) {
        super(t);
        byte[] data = this.getRecord().getData();
        this.version = IntegerHelper.getInt(data[0], data[1]);  /**在此处data数组发生异常，其为空数组**/
        this.substreamType = IntegerHelper.getInt(data[2], data[3]);
    }

**Comment by StableMutation** [comment]
### 问题已得到解决
该异常只发生在，你写入到同目录，同文件名时才发生。多次写入需要手动进行处理。
